name: fh-immuta-utils
dependencies:
  - python >=3.6
  - pip
  - boto3
  - click
  - psycopg2
  - pydantic
  - pytest
  - pyyaml
  - requests
  - six
  - sqlalchemy
  - toolz
  - tqdm
  - urllib3
  - pip:
    - datadog
    - hvac
    - pre_commit
    - pyathena
    - recommonmark
    - sphinx
    - sphinxcontrib.confluencebuilder
